apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvnfsmyapi
spec:
  storageClassName: nfs-nas
  capacity:
    storage: 2048Ki
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nasserver
    path: /share/nfs/myapi
