apiVersion: v1
kind: Service
metadata:
  name: myapi
spec:
  selector:
    app: myapi
  type: NodePort
  ports:
    - name: frontend
      protocol: TCP
      port: 8000
      nodePort: 30080
      targetPort: 8000
